// Countries actions
export const COUNTRIES_REQUEST = "COUNTRIES_REQUEST"
export const COUNTRIES_REQUEST_SUCCESS = "COUNTRIES_REQUEST_SUCCESS"
export const COUNTRIES_REQUEST_FAILURE = "COUNTRIES_REQUEST_FAILURE"

export const FILTER_COUNTRIES = "FILTER_COUNTRIES"
export const FILTER_COUNTRIES_CLEAR = "FILTER_COUNTRIES_CLEAR"
export const SAVE_LOCAL_COUNTRIES = "SAVE_LOCAL_COUNTRIES"