// Countries actions
export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST'
export const COUNTRIES_REQUEST_SUCCESS = 'COUNTRIES_REQUEST_SUCCESS'
export const COUNTRIES_REQUEST_FAILURE = 'COUNTRIES_REQUEST_FAILURE'

export const FILTER_COUNTRIES = 'FILTER_COUNTRIES'
export const FILTER_COUNTRIES_CLEAR = 'FILTER_COUNTRIES_CLEAR'
export const SAVE_LOCAL_COUNTRIES = 'SAVE_LOCAL_COUNTRIES'

// Tracks actions
export const TRACKS_REQUEST = 'TRACKS_REQUEST'
export const TRACKS_REQUEST_SUCCESS = 'TRACKS_REQUEST_SUCCESS'
export const TRACKS_REQUEST_FAILURE = 'TRACKS_REQUEST_FAILURE'

export const TRACK_LOVE_REQUEST = 'TRACK_LOVE_REQUEST'
export const TRACK_LOVE_REQUEST_SUCCESS = 'TRACK_LOVE_REQUEST_SUCCESS'
export const TRACK_LOVE_REQUEST_FAILURE = 'TRACK_LOVE_REQUEST_FAILURE'
export const TRACK_LOVE_REQ_RESET = 'TRACK_LOVE_REQ_RESET'

export const GET_LOVED_TRACKS_REQUEST = 'GET_LOVED_TRACKS_REQUEST'
export const GET_LOVED_TRACKS_SUCCESS = 'GET_LOVED_TRACKS_SUCCESS'
export const GET_LOVED_TRACKS_FAILURE = 'GET_LOVED_TRACKS_FAILURE'

export const MAP_LOVED_TRACKS = 'MAP_LOVED_TRACKS'
